### ISSUE TITLE
Needs license

### ISSUE THREAD

**Issue by est31** [rust-rfcs/unsafe-code-guidelines#20]
This repo has no license. That's bad! The later you are thinking about this, the harder it is to introduce licenses. So better think about it now.

**Comment by asajeffrey** [comment]
@est31 Good point. There was a bit of discussion at today's meeting (https://rust-lang.zulipchat.com/#narrow/stream/136281-wg-unsafe-code-guidelines/subject/meeting.202018-09-13/near/133894671).

The Rust book (https://github.com/rust-lang/book) and reference (https://github.com/rust-lang-nursery/reference) use joint MIT / Apache licenses.

Personally I find that a bit odd, since those are code licenses. I've usually used a CC license (https://creativecommons.org/) for docs.

**Comment by asajeffrey** [comment]
If we're expecting the unsafe code guidelines to be a companion to the language spec, and especially if we want to allow it to be merged, we pretty much have to be MIT/Apache licensed. Relicensing the reference at this point is essentially impossible (there are 169 contributors). So I think we're stuck with MIT/Apache.

**Comment by nikomatsakis** [comment]
Personally, I would prefer to follow the precedent of other Rust repositories. I checked in with @steveklabnik and indeed the MIT/APACHE licenses were chosen pretty deliberately, to keep things simpler and uniform (and because we believe that they apply).

Also, as @asajeffrey says, if we wind up having to relicense documentation, we've got a big job ahead of us anyway, and adding the UCG into the mix isn't a big difference. =)

**Comment by est31** [comment]
In [RFC 2044](http://rust-lang.github.io/rfcs/2044-license-rfcs.html), I've been arguing for MIT/Apache. See the points in the alternatives section.

**Comment by nikomatsakis** [comment]
Sounds like a win. Let's do it.

**Comment by nikomatsakis** [comment]
I actually thought I added LICENSE-MIT and LICENSE-APACHE -- I know I meant to -- but I guess I forgot. Luckily I think I'm the sole author of the content in the repo thus far =) (we could double check that, though).

**Comment by nikomatsakis** [comment]
OK, that's not true. There are a few others:

- @avadacatavra 
- @matklad 

both have commits. Could you all leave a comment stating that you agree to relicense under MIT/APACHE2?

**Comment by nikomatsakis** [comment]
See this PR: https://github.com/rust-rfcs/unsafe-code-guidelines/pull/21

**Comment by nikomatsakis** [comment]
Actually, @matklad and @RalfJung both fixed typos.

**Comment by matklad** [comment]
I’ve only fixed a tiny typo, but, just in case, I agree to relicense under MIT/APACHE

**Comment by RalfJung** [comment]
I agree to relicense under MIT/APACHE.

**Comment by avadacatavra** [comment]
I agree to relicense under MIT/APACHE.
